### ISSUE TITLE
Uncaught NoSuchNodeError if Exploration cannot be found in HDF

### ISSUE THREAD

**Issue by lu-kolb** [caglorithm/mopet#11]
## Description

Currently, if you try to load results of an exploration that has not been stored in the HDF, a `tables.exceptions.NoSuchNodeError` gets thrown that is not handled in `mopet` and terminates the python script.

I would suggest to catch the exception and log an error message that points out that the Exploration with the specified `exploration_name` has not been stored in the HDF file.
We could return either an empty DataFrame or throw a custom exception such as `ExplorationNotFound` holding the error message. If we throw an exception we can add it to the method docs so that users can react to it.

## Minimal Example
```python
from mopet import mopet
import numpy as np

def run(params):
    return {}

params = {"a": np.arange(0, 1, 0.5)}

ex = mopet.Exploration(run, params, exploration_name="testA")
ex.load_results()
```

```
Traceback (most recent call last):
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/synchronization/mopet_test.py", line 12, in <module>
    ex.load_results()
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/mopet/mopet.py", line 184, in load_results
    self._load_all_results(exploration_name, all=all)
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/mopet/mopet.py", line 446, in _load_all_results
    hdf_runs_group = self.h5file.get_node("/" + self.exploration_name, "runs")
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/tables/file.py", line 1642, in get_node
    node = self._get_node(nodepath)
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/tables/file.py", line 1590, in _get_node
    node = self._node_manager.get_node(nodepath)
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/tables/file.py", line 432, in get_node
    node = self.node_factory(key)
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/tables/group.py", line 1178, in _g_load_child
    node_type = self._g_check_has_child(childname)
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/testA/runs``
Closing remaining open files:exploration.h5...done
```

**Comment by caglorithm** [comment]
That's true, it would be good to catch that. Any suggestion how to check whether the exploration was saved or not? Maybe opening the hdf file and looking there instead of remembering as a attribute even.

**Comment by lu-kolb** [comment]
Yes checking the hdf file for an existing exploration sounds good. Do we save it as an attribute atm?

For this issue I would simply catch the `NoSuchNodeError` exception and throw a custom `NoSuchExploration` exception that is commented in the `load_results` method.

**Comment by caglorithm** [comment]
> For this issue I would simply catch the NoSuchNodeError exception and throw a custom NoSuchExploration exception 

That sounds like the way to go to me!

**Comment by lu-kolb** [comment]
Alright, I did this already on a side branch. Will create a PR in a couple of days

**Comment by lu-kolb** [comment]
Finished with 309dc06
