### ISSUE TITLE
int value im return dict führt zu AttributeError

### ISSUE THREAD

**Issue by lu-kolb** [caglorithm/mopet#3]
### Beschreibung
In der `_read_group_as_dict` Methode wird in der `if value.ndim == 0:` Condition ein 0-dim array ggfs in numpy.float64 umgewandelt. Jedoch kann `value` auch von Typ `int` sein, welcher kein `ndim` attribut besitzt. Das führt momentan zu einem nicht abgefangenen `AttributeError`.

### Minimales Beispiel:

```python
from mopet import mopet

def run(params):
    print(params)
    return {
        "test": 1
    }

params = { "a": [1, 2]}

ex = mopet.Exploration(run, params)
ex.run()
ex.load_results()
```
 
### Stacktrace:
```
Traceback (most recent call last):
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/synchronization/mopet_test.py", line 14, in <module>
    ex.load_results()
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/mopet/mopet.py", line 282, in load_results
    self._hdf_get_data_from_exploration(exploration_name)
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/mopet/mopet.py", line 318, in _hdf_get_data_from_exploration
    self._get_run_results(child, run_id)
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/mopet/mopet.py", line 328, in _get_run_results
    self.results[run_id] = self._read_group_as_dict(hdf_run)
  File "/Users/lrebscher/git/Synchronization-by-Uncorrelated-Noise/venv/lib/python3.7/site-packages/mopet/mopet.py", line 346, in _read_group_as_dict
    if value.ndim == 0:
AttributeError: 'int' object has no attribute 'ndim'
```

### Lösung

Den Zugriff auf `ndim` absichern mit: 
```python
if hasattr(value, 'ndim') and value.ndim == 0:`
```

**Comment by caglorithm** [comment]
Danke für's Issue! 

Ich würde Vorschlagen einen anderen Check zu machen:

```python
if isinstance(value, (int, float)) or value.ndim == 0:
```

**Comment by caglorithm** [comment]
Komisch, ich hab es ausgeführt aber bei mir läuft alles. 

![image](https://user-images.githubusercontent.com/7763212/83066143-e3f6d680-a064-11ea-8435-c3ba4ae6a048.png)

Der Fehler sollte nicht auftreten da kurz vor dieser Zeile steht
```python
                if not isinstance(value, np.ndarray):
                    value = np.array(value)
                # convert 0-dim arrays to floats
                if value.ndim == 0:
                    value = np.float(value)
```

**Comment by caglorithm** [comment]
Ich hatte ein PR lokal, den ich noch nicht gemerged hatte. Kannst du es mit der neuesten version 0.1.2 von `mopet` noch mal ausprobieren?

**Comment by lu-kolb** [comment]
Ja mit der 0.1.2 Version tritt das Problem nicht mehr auf!

**Comment by caglorithm** [comment]
Perfekt, gut dass du mich daran erinnert hast! Closing.
